services:
  server:
    container_name: garrysmod-breach-brasil
    restart: unless-stopped
    image: arctichusky/garrysmod-docker-arm64:0.1
    tty: true
    stdin_open: true
    #network_mode: host
    ports:
      - "27005:27005/udp"
      - "27015:27015"
      - "27015:27015/udp"
    environment:
      - ARGS=""
      - GAMEMODE=${GAMEMODE}
      - MAP=${MAP}
      - MAXPLAYERS=${MAXPLAYERS}
      - PORT=${PORT}
      - NAME=${NAME}
      - GSLT=${GSLT}
      - PRODUCTION=${PRODUCTION}
      - ARM64_DEVICE=${ARM64_DEVICE}
      # - AUTHKEY=
      # - GM_CLIENTPORT=27005 ??
    volumes:
      - /mnt/vol/garrysmod/breach-brasil/addons:/home/steam/server/addons
      - /mnt/vol/garrysmod/breach-brasil/cfg:/home/steam/server/cfg
      - /mnt/vol/garrysmod/breach-brasil/cfg/mount.cfg:/home/steam/server/cfg/mount.cfg
      - /mnt/vol/garrysmod/breach-brasil/cfg/server.cfg:/home/steam/server/cfg/server.cfg
      - /mnt/vol/garrysmod/breach-brasil/data:/home/steam/server/data
      - /mnt/vol/garrysmod/breach-brasil/gamemodes:/home/steam/server/gamemodes
      - /mnt/vol/garrysmod/breach-brasil/lua:/home/steam/server/lua
      - /mnt/vol/garrysmod/breach-brasil/maps:/home/steam/server/maps
      - /mnt/vol/garrysmod/breach-brasil/sv.db:/home/steam/server/sv.db
